version: 0.2
phases:
  build:
    commands:
      - docker run -i --rm -v "${PWD}:/cfnlint" -w /cfnlint leipert/atom-apm sh -c "apm install && \
          start-stop-daemon --start --pidfile /tmp/xvfb_99.pid --make-pidfile \
            --background --exec /usr/bin/Xvfb -- :99 -screen 0 1024x768x24 -ac \
            +extension GLX +extension RANDR +render -noreset && \
            sleep 3 && \
            export DISPLAY=:99 && \
            apm test"
      - docker run -i --rm -v "${PWD}:/cfnlint" -w /cfnlint python:3.6-alpine3.7 sh -c "pip install tox;tox -e py36,pylint36"
